on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: |
          sudo apt-get install -yq --no-install-recommends emscripten
          emcc factorial.c -o factorial.html
          emcc hello.c -o hello.html
          git add .
          if git diff --cached --exit-code >/dev/null; then exit 0; fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Build wasm"
          git push
