on: [push]
jobs:
  build-factorial:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: |
          sudo apt-get install emscripten
          emcc factorial.c -o factorial.html
          git add .
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Build factorial"
          git push
