on:
  push:
    branches:
      - main
jobs:
  build:
    env:
      ver: 0.0.1
      msg: Second dev release
      cancel: ''
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
      - name: Check tag
        run: |
          tag=v$ver
          echo "tag=$tag" >> "$GITHUB_ENV"
          # Fetch all tags
          git fetch origin 'refs/tags/*:refs/tags/*'
          # Cancel if tag already exists
          if [ -n "$(git tag --list $tag)" ]; then echo 'cancel=true' >> "$GITHUB_ENV"; fi
      - name: Get dependencies
        if: ${{ ! env.cancel }}
        run: |
          sudo rm /var/lib/man-db/auto-update
          sudo apt-get install -yq --no-install-recommends emscripten
      - name: Build code
        if: ${{ ! env.cancel }}
        run: |
          emcc factorial.c -o factorial-$ver.html
          emcc hello.c -o hello-$ver.html
      - name: Create release
        if: ${{ ! env.cancel }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag -a $tag -m "$msg"
          git push origin $tag
          gh release create $tag hello-$ver.* factorial-$ver.* --verify-tag --generate-notes
