on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: |
          ver=0.0.0
          tag=v$ver
          msg="First dev release"
          # Exit if tag already exists
          if [ -n "$(git tag --list $tag)" ]; then exit 0; fi
          sudo apt-get install -yq --no-install-recommends emscripten
          emcc factorial.c -o factorial-$ver.html
          emcc hello.c -o hello-$ver.html
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag -a $tag -m "$msg"
          git push origin $tag
          gh release create $tag hello-$ver.* factorial-$ver.* --verify-tag --generate-notes
