on: [push]
jobs:
  invade-other-repository:
    runs-on: ubuntu-latest
    env:
      SITE_REPO_URL: https://github.com/martinjos/martinjos.github.io
      SITE_BRANCH: master-R
      FILE_DST_NAME: you_are_insecure.txt
    steps:
      - name: Check URL
        run: test "$SITE_REPO_URL" = "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY_OWNER/$GITHUB_REPOSITORY_OWNER.github.io"
      - name: Fetch github.io site
        run: git clone --branch "$SITE_BRANCH" "$SITE_REPO_URL" site
      - name: Make new commit
        run: |
          cd site
          git config --global user.name 'Martin Sidaway'
          git config --global user.email '2389068+martinjos@users.noreply.github.com'
          echo 'GITHUB_TOKEN can do more than it should!' > "$FILE_DST_NAME"
          git add .
          git commit -m 'This commit should _not_ be successfully pushed to GitHub'
          cd ..
      - name: Log
        run: |
          cd site
          git log --format=fuller --decorate
          cd ..
      - name: Push
        run: |
          cd site
          git push
          cd ..
